# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIKitArcade' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'SDWebImage', :modular_headers => true
  # Pods for UIKitArcade

  target 'UIKitArcadeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
